### ISSUE TITLE
Error: no module named shodan

### ISSUE THREAD

**Issue by Babushkadecesarw** [jimywork/shodanwave#17]
Hi, i installed everything i needed to run shodanwave on my kali 2021.3 system but it shows the error above, i tried updating shodan but it didnt help.

**Comment by is107964** [comment]
I have the same issue:
Error: No module named shodan 

Try this ... pip install -r /path/to/requirements.txt
Traceback (most recent call last):
  File "./shodanwave.py", line 357, in <module>
    main()
  File "./shodanwave.py", line 37, in main
    Graph = Figlet(font='slant')
NameError: global name 'Figlet' is not defined
